// <auto-generated />
//
// To parse this JSON data, add NuGet 'Newtonsoft.Json' then do:
//
//    using QuickType;
//
//    var speaker = Speaker.FromJson(jsonString);

using System;
using Newtonsoft.Json;

namespace ConferenceApp.Services
{

    public class LinkDto
    {
        [JsonProperty("title")]
        public string Title { get; set; }

        [JsonProperty("url")]
        public Uri Url { get; set; }

        [JsonProperty("linkType")]
        public string LinkType { get; set; }
    }
}
